# Generated by Django 4.2.6 on 2023-11-02 19:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='A book')),
                ('image', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('content', models.FileField(upload_to='')),
                ('contributors', models.CharField(max_length=255)),
                ('contributors_role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
                ('ratings', models.CharField(choices=[('1', 'One Star'), ('2', 'Two Stars'), ('3', 'Three Stars'), ('4', 'Four Stars'), ('5', 'Five Stars')], default='1', max_length=4)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('creator', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
