# Generated by Django 4.2.6 on 2023-11-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors2', '0001_initial'),
        ('books', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='book_set', to='authors2.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(default='hi'),
        ),
    ]
